# Generated by Django 5.2.16 on 2026-07-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_expires_on',
            field=models.DateField(blank=True, help_text='If set, this user cannot log in after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
