# Generated by Django 5.2.16 on 2026-07-14 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsnapshot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
